name: Release

on:
  push:
    tags:
      - v*
  repository_dispatch:
    types: [trigger-release]
  workflow_dispatch:


jobs:
  deploy-central:
    runs-on: ubuntu-latest
    container: maven:3.6.3-amazoncorretto-11
    env:
      ZEPBEN_GPG_KEY: ${{ secrets.ZEPBEN_GPG_KEY_B64 }}
      MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache maven deps
        uses: actions/cache@v2
        with:
          path: /maven
          key: maven

      - name: Maven deploy to Central
        run: |
          echo "$ZEPBEN_GPG_KEY" | base64 -d > zepben-gpg.key
          gpg2 --batch --import zepben-gpg.key
          mvn clean deploy -f pom.xml -P release,ossrh -s for-ci-build-image/maven-settings.xml -Dossrh.server.username=$OSSRH_USERNAME -Dossrh.server.password=$OSSRH_PASSWORD -Dgpg.key.id=$GPG_KEY_ID -Dgpg.key.password=$GPG_KEY_PASSWORD
        shell: bash

      - name: Trigger container build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          event-type: build-container